Fat 135
folio-org/folio-integration-tests pull request #236
Opened 2021-08-10 07:36 UTC by Serhii-Zdorenko

### **Purpose**
MODTAGS: Implement API Karate tests

### **Learning**
https://issues.folio.org/browse/FAT-135

2021-08-10 10:17 UTC, psmagin reviewed
Please add negative scenarios:
* when trying to create a new tag with label that already exists in the system;
* when trying to update a tag with a label that already exists in the system.

2021-08-10 13:46 UTC, Serhii-Zdorenko commented
@psmagin Done

2021-08-11 07:41 UTC, psmagin approved these changes
Please, include ticket number to your commit messages in future.

2021-08-11 09:09 UTC, oleksandr-dekin requested changes

2021-08-11 09:09 UTC, oleksandr-dekin commented on mod-tags/src/test/resources/domain/tags/features/tags.feature
> +    And match response.totalRecords == 2
You can add verification for label and description

2021-08-11 09:09 UTC, oleksandr-dekin commented on mod-tags/src/test/resources/domain/tags/features/tags.feature
> +    When method POST
You should verify status for every request. Please, add: `Then status 201`

2021-08-11 09:09 UTC, oleksandr-dekin commented on mod-tags/src/test/resources/domain/tags/features/tags.feature
> +    When method GET
The same, please, add verification status

2021-08-11 09:09 UTC, oleksandr-dekin commented on mod-tags/src/test/resources/domain/tags/features/tags.feature
> +    Given path 'tags/' + first_tag.id
Please, avoid unnecessary character `/` 
```suggestion
    Given path 'tags', first_tag.id
```

2021-08-11 09:09 UTC, oleksandr-dekin commented on mod-tags/src/test/resources/domain/tags/features/tags.feature
> +    Given path 'tags/' + response.id
```suggestion
    Given path 'tags', response.id
```

2021-08-11 09:09 UTC, oleksandr-dekin commented on mod-tags/src/test/resources/domain/tags/features/tags.feature
> +    Given path 'tags/' + test_tag.id
Given path 'tags/' + test_tag.id
```suggestion
    Given path 'tags', test_tag.id
```

2021-08-11 09:09 UTC, oleksandr-dekin commented on mod-tags/src/test/resources/domain/tags/features/tags.feature
> +    Given path 'tags/' + test_tag.id
```suggestion
    Given path 'tags', test_tag.id
```

2021-08-11 13:20 UTC, oleksandr-dekin approved these changes

2021-08-11 13:46 UTC, merged