FAT-936: API tests for data import converter storage
folio-org/folio-integration-tests pull request #248
Opened 2021-08-17 12:35 UTC by TetianaParanich

1.

2021-08-17 12:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/folio-integration-tests?pullRequest=248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/folio-integration-tests?pullRequest=248) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/folio-integration-tests?pullRequest=248) it.</sub>

2021-08-17 13:40 UTC, KaterynaSenchenko requested changes
Please change the structure of created Job Profile - it should be one profile, which contains three action profiles (not three separate Job Profiles for each action)

2021-08-18 10:13 UTC, TetianaParanich commented
> Please change the structure of created Job Profile - it should be one profile, which contains three action profiles (not three separate Job Profiles for each action)

Thanks, @KaterynaSenchenko, I took into account the comments and made changes.

2021-08-18 10:27 UTC, KaterynaSenchenko commented on mod-data-import-converter-storage/src/main/resources/domain/mod-data-import-converter-storage/features/create-profiles-and-remove-them.feature
> +  Scenario: Create MARC-to-Instance
```suggestion
  Scenario: Create Job Profile for create Instance, Holdings, Item
```

2021-08-18 10:27 UTC, KaterynaSenchenko approved these changes

2021-08-18 10:57 UTC, VRohach approved these changes

2021-08-18 11:48 UTC, bisecomsergiy approved these changes

2021-08-19 12:08 UTC, merged