FAT-192 add test plan
folio-org/folio-integration-tests pull request #271
Opened 2021-09-06 06:41 UTC by Serhii-Zdorenko

### Purpose
mod-kb-ebsco-java: Create test plan to cover functionality with API Karate test - KB credentials

### Approach:
Create test plan to cover functionality with API Karate test

### Learning
https://issues.folio.org/browse/FAT-192

2021-09-06 17:20 UTC, psmagin requested changes

2021-09-06 17:20 UTC, psmagin commented on mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/kb-credentials.feature
> +  Scenario: GET /eholdings/kb-credentials should return status 200 and json file
1. No JSON file is returning by any endpoint of the API.
2. Please change the names of scenarios to be more specific. Like "Should return all existed KB credentials" or "Should create new valid KB credentials"

2021-09-06 17:20 UTC, psmagin commented on mod-kb-ebsco-java/src/main/resources/domain/mod-kb-ebsco-java/features/kb-credentials.feature
> +  Scenario: DELETE /eholdings/kb-credentials{id} should return status 400 and json if customerId invalid
Duplicate scenario.

2021-09-09 07:56 UTC, psmagin approved these changes

2021-09-09 08:10 UTC, oleksandr-dekin approved these changes

2021-09-09 08:36 UTC, merged