FAT-1514 Karate Tests: Create MARC holdings via Inventory app
folio-org/folio-integration-tests pull request #453
Opened 2022-02-21 08:56 UTC by Shans-Kaluhin

### Approach
- Optimize creation

### Learn
[FAT-1514](https://issues.folio.org/browse/FAT-1514)

2022-02-22 09:35 UTC, psmagin requested changes
Please move logic of creating MARC holdings from inventory to quick-marc API.

2022-02-23 00:43 UTC, Shans-Kaluhin commented
> Please move logic of creating MARC holdings from inventory to quick-marc API.

Hello Pavel, I opened [pull request](https://github.com/folio-org/folio-integration-tests/pull/459) for quick-marc API.
But we still can merge this one to improve readability of tests.
I removed new test cases here

2022-03-02 12:51 UTC, viacheslavkol approved these changes

2022-03-07 20:06 UTC, psmagin approved these changes

2022-03-09 04:58 UTC, merged