FAT-1514 Karate Tests: Create MARC holdings via Inventory app
folio-org/folio-integration-tests pull request #459
Opened 2022-02-23 00:40 UTC by Shans-Kaluhin

### Approach
- Optimize record creation way
- Setup default data for mod-inventory 

### Test cases
- Test Instance HRID creation (004 field)
- Test for 852 $b location code already exist
- Check a 008 Tag
- Test Instance HRID error if not linked

### Learn
[FAT-1514](https://issues.folio.org/browse/FAT-1514)

2022-02-23 12:08 UTC, psmagin requested changes
I can't see test cases for holdings creation via quickMarc. The test cases are about viewing created by the data-import record. Please, add test cases for creating holdings via quick-marc, see API documentation for the endpoint that is responsible for this action: https://s3.amazonaws.com/foliodocs/api/mod-quick-marc/s/records-editor.html#tag/records-editor/paths/~1records/post

2022-03-07 20:11 UTC, psmagin requested changes
There are still no cases where this endpoint is used: https://s3.amazonaws.com/foliodocs/api/mod-quick-marc/s/records-editor.html#tag/records-editor/paths/~1records/post

2022-03-10 13:12 UTC, psmagin approved these changes

2022-03-10 13:15 UTC, ALiemeshka approved these changes

2022-03-10 13:19 UTC, merged