Check out item to borrowing site from owning site added
folio-org/folio-integration-tests pull request #649
Opened 2022-07-06 10:35 UTC by Arghya22

Purpose : Check out item to borrowing site from owning site (API : POST transactions/{itemBarcode}/check-out-item/{servicePointId} ) 

=========================

Issue : 

While creating Item Hold , api return success status , but in the background (async)  method : createItemHoldRequest  throwing exception as follows  : 
{
  "localBibId": "it00000000085",
  "reason": "Request not permitted",
  "reasonCode": 7,
  "patronName": "Atreides, Leto II"
}

as a result transaction is getting canceled and checkout-item api failing by showing as follows : 
{
  "message": "INN-Reach transaction is not found by itemBarcode: 7010",
  "code": "404"
}

2022-07-06 11:06 UTC, oliinyko commented on mod-inn-reach/src/main/resources/volaris/mod-inn-reach/global/mod-item-util.feature
> +Feature: setup user data feature
there is already a feature to create inventory data -`mod_inventory_init_data.feature` where the instance is being created, just update it to create holding and item as well.

2022-07-11 07:38 UTC, gurleenkaurbp requested changes

2022-07-11 07:38 UTC, gurleenkaurbp commented on mod-inn-reach/src/main/resources/karate-config.js
> +     karate.callSingle('classpath:volaris/mod-inn-reach/global/add-okapi-permissions.feature', config);
Please revert this change

2022-07-11 07:46 UTC, arin-epm approved these changes

2022-07-11 07:46 UTC, nirmalr-shah approved these changes

2022-07-11 07:47 UTC, merged