FAT-3638 Karate Tests: Linked Authority updates
folio-org/folio-integration-tests pull request #873
Opened 2023-02-16 05:04 UTC by Shans-Kaluhin

2023-02-16 09:27 UTC, psmagin requested changes

2023-02-16 09:27 UTC, psmagin commented on mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-linking-records.feature
> +    And match response.parsedRecord.content.fields[*].100.subfields[*].a contains only 'Updated'
The instance doesn't have subfields

2023-02-16 09:27 UTC, psmagin commented on mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-linking-records.feature
> +    And match response.parsedRecord.content.fields[*].100.subfields[*].9 == []
Also check that instance has authorityId=null

2023-02-16 09:27 UTC, psmagin commented on mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-linking-records.feature
> +Feature: linking-rules tests
It's not linking-rules tests

2023-02-16 09:29 UTC, psmagin commented on mod-quick-marc/src/main/resources/spitfire/mod-quick-marc/features/quick-marc-linking-records.feature
> +    And match response.parsedRecord.content.fields[*].100.subfields[*].a contains only 'Updated'
How does it's even passed? Is this condition workable, do they really check smth?

2023-02-21 08:23 UTC, psmagin approved these changes

2023-02-21 09:18 UTC, hasanepam approved these changes

2023-02-21 12:02 UTC, viacheslavkol approved these changes

2023-02-22 12:01 UTC, merged